[project]
name = "mcp-server-documentation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckduckgo-search>=7.5.2",
    "fastapi>=0.115.11",
    "httpx>=0.28.1",
    "mcp[cli]>=1.4.1",
]
